apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftclusters.mcoperator.anvilpowered.org
spec:
  group: mcoperator.anvilpowered.org
  names:
    kind: MinecraftCluster
    plural: minecraftclusters
    singular: minecraftcluster
    shortNames:
      - mcc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A MinecraftCluster is group of cohesive minecraft servers
          type: object
          properties:
            spec:
              type: object
              properties:
                minecraftStorageName:
                  type: string
              required:
                - minecraftStorageName
          required:
            - spec
