apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftstorages.mcoperator.anvilpowered.org
spec:
  group: mcoperator.anvilpowered.org
  names:
    kind: MinecraftStorage
    plural: minecraftstorages
    singular: minecraftstorage
    shortNames:
      - mcst
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: A MinecraftStorage defines where minecraft server files are stored
          type: object
          properties:
            spec:
              type: object
              properties:
                primaryVolumeSpec:
                  type: object
                  properties:
                    storageClassName:
                      type: string
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                          additionalProperties:
                            type: string
                            pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                        requests:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                          additionalProperties:
                            type: string
                            pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
