apiVersion: org.anvilpowered/v1alpha1
kind: MinecraftStatefulServerTemplate
metadata:
  name: example
  namespace: example
spec:
  image: "itzg/minecraft-server:latest"
  basePodTemplateSpec:
    containers:
      - name: minecraft
        env:
          - name: PLUGINS
            value: |
              http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/luckperms-proxy/1568/bukkit/loader/LuckPerms-Bukkit-5.4.151.jar
              http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/4drian3d/SignedVelocity/releases/download/1.3.0/SignedVelocity-Paper-1.3.0.jar
              http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/mc-bin/griefdefender/griefdefender-bukkit-3.0.3.jar
              https://cdn.modrinth.com/data/hXiIvTyT/versions/puUfqBpY/EssentialsX-2.20.1.jar
